import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import useSWR from 'swr'

import Footer from "./components/Footer";
import Banner from "./components/Banner";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Recipe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Navbar></Navbar>
         <Toaster />
        <div className="min-h-screen">
          {children}
        </div>
        <Footer></Footer>
      </body>  
      </NextAuthSessionProvider>
      
    </html>
  );
}
