import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/providers/NextAuthSessionProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Recipe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthProvider>
       <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Navbar></Navbar>
         <Toaster />
        <div className="min-h-screen">
          {children}
        </div>
        <Footer></Footer>
      </body>  
      </NextAuthProvider>
     
     
      
    </html>
  );
}
